name: Formatting

on:
   push:
      branches: ["master"]
   pull_request:
      branches: ["master"]

jobs:
  checkFormatting:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-python@v4
           with:
              python-version: "3.10"
         - name: Check java formatting
           run: |
             # get the file that checks formatting using google-java-format
             curl https://raw.githubusercontent.com/plume-lib/run-google-java-format/master/check-google-java-format.py -o check-google-java-format.py
             shopt -s globstar
             python check-google-java-format.py **/*.java
         - name: Check Js formatting
           uses: actionsx/prettier@v2
           with:
             args: --check exam/ # only run prettier on js files
